### ISSUE TITLE
Invalid Hand Calculations?

### ISSUE THREAD

**Issue by hailwood** [mitch-b/typedeck#9]
## I'm submitting a ...
- [x] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository
- [ ] question about how to use this project

## Summary
Hey @mitch-b,

It looks like we might have an issue with calculating the winning hands.
I only came across this last night at about 1am... so I haven't had a chance to debug it properly, so I'll provide some more information or a PR to fix it tonight but figure depending on your timezone you might get there first. This is using the new poker-hand-details branch, so I'm not sure if it's on the main branch yet.

Try running this game through:

Community cards: 7S 3S 4C 5H 6D
Player 1's name and two cards: Bob 2C 8D
Player 2's name and two cards: Joe 8S 9C

Result:
1 Joe High Card Nine
2 Bob High Card Eight

...what? Shouldn't that be a straight for both players?

```js
`${result.toString()} ${result.scoringHandCardNames.map(cn => CardName[cn]).join(' ')}`
```

**Comment by mitch-b** [comment]
You're right ... something's definitely wrong with how it's reporting the hand type. 

> https://runkit.com/mitch-b/poker-scoring-scratchpad-9

It has the proper `value`, but the `handType` is not being set as we'd expect. Strange, and a critical bug, but shouldn't be too hard to dig into. Weird that tests are passing, but in-practice, I can't seem to get the proper result out.

**Comment by mitch-b** [comment]
Sorry to keep bundling these into the [`feature/poker-hand-details`](https://github.com/mitch-b/typedeck/tree/feature/poker-hand-details) branch, but this bug was definitely there, and it was due to improper combination building.

I've adjusted this to use same Combination producing function as elsewhere in the code and it works as I expected. I added a new unit test to capture this. 

I will close this issue once this branch gets merged in.

Thanks for your help with this library. 🎉
